//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFIS360WebApp.UserAccessControlServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessControl", Namespace="http://localhost/AFIS360Webservice")]
    [System.SerializableAttribute()]
    public partial class AccessControl : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessEnrollmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessFingerprintMatchingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessUserMgmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessAuditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessFindField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessDataImportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessDataExportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessMultiMatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessClientSetupField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AccessLogin {
            get {
                return this.AccessLoginField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessLoginField, value) != true)) {
                    this.AccessLoginField = value;
                    this.RaisePropertyChanged("AccessLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AccessEnrollment {
            get {
                return this.AccessEnrollmentField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessEnrollmentField, value) != true)) {
                    this.AccessEnrollmentField = value;
                    this.RaisePropertyChanged("AccessEnrollment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AccessFingerprintMatching {
            get {
                return this.AccessFingerprintMatchingField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessFingerprintMatchingField, value) != true)) {
                    this.AccessFingerprintMatchingField = value;
                    this.RaisePropertyChanged("AccessFingerprintMatching");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AccessUserMgmt {
            get {
                return this.AccessUserMgmtField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessUserMgmtField, value) != true)) {
                    this.AccessUserMgmtField = value;
                    this.RaisePropertyChanged("AccessUserMgmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AccessAudit {
            get {
                return this.AccessAuditField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessAuditField, value) != true)) {
                    this.AccessAuditField = value;
                    this.RaisePropertyChanged("AccessAudit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string AccessFind {
            get {
                return this.AccessFindField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessFindField, value) != true)) {
                    this.AccessFindField = value;
                    this.RaisePropertyChanged("AccessFind");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string AccessDataImport {
            get {
                return this.AccessDataImportField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessDataImportField, value) != true)) {
                    this.AccessDataImportField = value;
                    this.RaisePropertyChanged("AccessDataImport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string AccessDataExport {
            get {
                return this.AccessDataExportField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessDataExportField, value) != true)) {
                    this.AccessDataExportField = value;
                    this.RaisePropertyChanged("AccessDataExport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string AccessMultiMatch {
            get {
                return this.AccessMultiMatchField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessMultiMatchField, value) != true)) {
                    this.AccessMultiMatchField = value;
                    this.RaisePropertyChanged("AccessMultiMatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string AccessClientSetup {
            get {
                return this.AccessClientSetupField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessClientSetupField, value) != true)) {
                    this.AccessClientSetupField = value;
                    this.RaisePropertyChanged("AccessClientSetup");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/AFIS360Webservice", ConfigurationName="UserAccessControlServiceRef.UserAccessControlSoap")]
    public interface UserAccessControlSoap {
        
        // CODEGEN: Generating message contract since element name role from namespace http://localhost/AFIS360Webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/AFIS360Webservice/getAccessControl", ReplyAction="*")]
        AFIS360WebApp.UserAccessControlServiceRef.getAccessControlResponse getAccessControl(AFIS360WebApp.UserAccessControlServiceRef.getAccessControlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/AFIS360Webservice/getAccessControl", ReplyAction="*")]
        System.Threading.Tasks.Task<AFIS360WebApp.UserAccessControlServiceRef.getAccessControlResponse> getAccessControlAsync(AFIS360WebApp.UserAccessControlServiceRef.getAccessControlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccessControlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAccessControl", Namespace="http://localhost/AFIS360Webservice", Order=0)]
        public AFIS360WebApp.UserAccessControlServiceRef.getAccessControlRequestBody Body;
        
        public getAccessControlRequest() {
        }
        
        public getAccessControlRequest(AFIS360WebApp.UserAccessControlServiceRef.getAccessControlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/AFIS360Webservice")]
    public partial class getAccessControlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string role;
        
        public getAccessControlRequestBody() {
        }
        
        public getAccessControlRequestBody(string role) {
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccessControlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAccessControlResponse", Namespace="http://localhost/AFIS360Webservice", Order=0)]
        public AFIS360WebApp.UserAccessControlServiceRef.getAccessControlResponseBody Body;
        
        public getAccessControlResponse() {
        }
        
        public getAccessControlResponse(AFIS360WebApp.UserAccessControlServiceRef.getAccessControlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/AFIS360Webservice")]
    public partial class getAccessControlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AFIS360WebApp.UserAccessControlServiceRef.AccessControl getAccessControlResult;
        
        public getAccessControlResponseBody() {
        }
        
        public getAccessControlResponseBody(AFIS360WebApp.UserAccessControlServiceRef.AccessControl getAccessControlResult) {
            this.getAccessControlResult = getAccessControlResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserAccessControlSoapChannel : AFIS360WebApp.UserAccessControlServiceRef.UserAccessControlSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserAccessControlSoapClient : System.ServiceModel.ClientBase<AFIS360WebApp.UserAccessControlServiceRef.UserAccessControlSoap>, AFIS360WebApp.UserAccessControlServiceRef.UserAccessControlSoap {
        
        public UserAccessControlSoapClient() {
        }
        
        public UserAccessControlSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserAccessControlSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAccessControlSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAccessControlSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AFIS360WebApp.UserAccessControlServiceRef.getAccessControlResponse AFIS360WebApp.UserAccessControlServiceRef.UserAccessControlSoap.getAccessControl(AFIS360WebApp.UserAccessControlServiceRef.getAccessControlRequest request) {
            return base.Channel.getAccessControl(request);
        }
        
        public AFIS360WebApp.UserAccessControlServiceRef.AccessControl getAccessControl(string role) {
            AFIS360WebApp.UserAccessControlServiceRef.getAccessControlRequest inValue = new AFIS360WebApp.UserAccessControlServiceRef.getAccessControlRequest();
            inValue.Body = new AFIS360WebApp.UserAccessControlServiceRef.getAccessControlRequestBody();
            inValue.Body.role = role;
            AFIS360WebApp.UserAccessControlServiceRef.getAccessControlResponse retVal = ((AFIS360WebApp.UserAccessControlServiceRef.UserAccessControlSoap)(this)).getAccessControl(inValue);
            return retVal.Body.getAccessControlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AFIS360WebApp.UserAccessControlServiceRef.getAccessControlResponse> AFIS360WebApp.UserAccessControlServiceRef.UserAccessControlSoap.getAccessControlAsync(AFIS360WebApp.UserAccessControlServiceRef.getAccessControlRequest request) {
            return base.Channel.getAccessControlAsync(request);
        }
        
        public System.Threading.Tasks.Task<AFIS360WebApp.UserAccessControlServiceRef.getAccessControlResponse> getAccessControlAsync(string role) {
            AFIS360WebApp.UserAccessControlServiceRef.getAccessControlRequest inValue = new AFIS360WebApp.UserAccessControlServiceRef.getAccessControlRequest();
            inValue.Body = new AFIS360WebApp.UserAccessControlServiceRef.getAccessControlRequestBody();
            inValue.Body.role = role;
            return ((AFIS360WebApp.UserAccessControlServiceRef.UserAccessControlSoap)(this)).getAccessControlAsync(inValue);
        }
    }
}
