//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFIS360WebApp.AuditLogServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/AFIS360Webservice", ConfigurationName="AuditLogServiceRef.AuditLogServiceSoap")]
    public interface AuditLogServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/AFIS360Webservice/updateAuditLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Person))]
        AFIS360WebApp.AuditLogServiceRef.Status updateAuditLog(AFIS360WebApp.AuditLogServiceRef.User webUser, AFIS360WebApp.AuditLogServiceRef.ActivityLog webActivityLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/AFIS360Webservice/updateAuditLog", ReplyAction="*")]
        System.Threading.Tasks.Task<AFIS360WebApp.AuditLogServiceRef.Status> updateAuditLogAsync(AFIS360WebApp.AuditLogServiceRef.User webUser, AFIS360WebApp.AuditLogServiceRef.ActivityLog webActivityLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/AFIS360Webservice/createAuditLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Person))]
        AFIS360WebApp.AuditLogServiceRef.Status createAuditLog(AFIS360WebApp.AuditLogServiceRef.User webUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/AFIS360Webservice/createAuditLog", ReplyAction="*")]
        System.Threading.Tasks.Task<AFIS360WebApp.AuditLogServiceRef.Status> createAuditLogAsync(AFIS360WebApp.AuditLogServiceRef.User webUser);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/AFIS360Webservice")]
    public partial class User : Person {
        
        private long idField;
        
        private string personIdField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string userRoleField;
        
        private string stationIdField;
        
        private string stationedAddressField;
        
        private string stationedCityField;
        
        private string stationedCountryField;
        
        private string activeStatusField;
        
        private System.DateTime serviceStartDateField;
        
        private System.DateTime serviceEndDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PersonId {
            get {
                return this.personIdField;
            }
            set {
                this.personIdField = value;
                this.RaisePropertyChanged("PersonId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UserRole {
            get {
                return this.userRoleField;
            }
            set {
                this.userRoleField = value;
                this.RaisePropertyChanged("UserRole");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string StationId {
            get {
                return this.stationIdField;
            }
            set {
                this.stationIdField = value;
                this.RaisePropertyChanged("StationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string StationedAddress {
            get {
                return this.stationedAddressField;
            }
            set {
                this.stationedAddressField = value;
                this.RaisePropertyChanged("StationedAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string StationedCity {
            get {
                return this.stationedCityField;
            }
            set {
                this.stationedCityField = value;
                this.RaisePropertyChanged("StationedCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string StationedCountry {
            get {
                return this.stationedCountryField;
            }
            set {
                this.stationedCountryField = value;
                this.RaisePropertyChanged("StationedCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ActiveStatus {
            get {
                return this.activeStatusField;
            }
            set {
                this.activeStatusField = value;
                this.RaisePropertyChanged("ActiveStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime ServiceStartDate {
            get {
                return this.serviceStartDateField;
            }
            set {
                this.serviceStartDateField = value;
                this.RaisePropertyChanged("ServiceStartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.DateTime ServiceEndDate {
            get {
                return this.serviceEndDateField;
            }
            set {
                this.serviceEndDateField = value;
                this.RaisePropertyChanged("ServiceEndDate");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(User))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/AFIS360Webservice")]
    public partial class Person : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Fingerprint[] fingerprintsField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Fingerprint[] Fingerprints {
            get {
                return this.fingerprintsField;
            }
            set {
                this.fingerprintsField = value;
                this.RaisePropertyChanged("Fingerprints");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/AFIS360Webservice")]
    public partial class Fingerprint : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] asImageDataField;
        
        private byte[] templateField;
        
        private Finger fingerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] AsImageData {
            get {
                return this.asImageDataField;
            }
            set {
                this.asImageDataField = value;
                this.RaisePropertyChanged("AsImageData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] Template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
                this.RaisePropertyChanged("Template");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Finger Finger {
            get {
                return this.fingerField;
            }
            set {
                this.fingerField = value;
                this.RaisePropertyChanged("Finger");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/AFIS360Webservice")]
    public enum Finger {
        
        /// <remarks/>
        Any,
        
        /// <remarks/>
        RightThumb,
        
        /// <remarks/>
        LeftThumb,
        
        /// <remarks/>
        RightIndex,
        
        /// <remarks/>
        LeftIndex,
        
        /// <remarks/>
        RightMiddle,
        
        /// <remarks/>
        LeftMiddle,
        
        /// <remarks/>
        RightRing,
        
        /// <remarks/>
        LeftRing,
        
        /// <remarks/>
        RightLittle,
        
        /// <remarks/>
        LeftLittle,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/AFIS360Webservice")]
    public partial class Status : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusCodeField;
        
        private string statusDescField;
        
        private long auditLogIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusDesc {
            get {
                return this.statusDescField;
            }
            set {
                this.statusDescField = value;
                this.RaisePropertyChanged("StatusDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long AuditLogId {
            get {
                return this.auditLogIdField;
            }
            set {
                this.auditLogIdField = value;
                this.RaisePropertyChanged("AuditLogId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/AFIS360Webservice")]
    public partial class ActivityLog : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] activityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] Activity {
            get {
                return this.activityField;
            }
            set {
                this.activityField = value;
                this.RaisePropertyChanged("Activity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuditLogServiceSoapChannel : AFIS360WebApp.AuditLogServiceRef.AuditLogServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuditLogServiceSoapClient : System.ServiceModel.ClientBase<AFIS360WebApp.AuditLogServiceRef.AuditLogServiceSoap>, AFIS360WebApp.AuditLogServiceRef.AuditLogServiceSoap {
        
        public AuditLogServiceSoapClient() {
        }
        
        public AuditLogServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuditLogServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuditLogServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuditLogServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AFIS360WebApp.AuditLogServiceRef.Status updateAuditLog(AFIS360WebApp.AuditLogServiceRef.User webUser, AFIS360WebApp.AuditLogServiceRef.ActivityLog webActivityLog) {
            return base.Channel.updateAuditLog(webUser, webActivityLog);
        }
        
        public System.Threading.Tasks.Task<AFIS360WebApp.AuditLogServiceRef.Status> updateAuditLogAsync(AFIS360WebApp.AuditLogServiceRef.User webUser, AFIS360WebApp.AuditLogServiceRef.ActivityLog webActivityLog) {
            return base.Channel.updateAuditLogAsync(webUser, webActivityLog);
        }
        
        public AFIS360WebApp.AuditLogServiceRef.Status createAuditLog(AFIS360WebApp.AuditLogServiceRef.User webUser) {
            return base.Channel.createAuditLog(webUser);
        }
        
        public System.Threading.Tasks.Task<AFIS360WebApp.AuditLogServiceRef.Status> createAuditLogAsync(AFIS360WebApp.AuditLogServiceRef.User webUser) {
            return base.Channel.createAuditLogAsync(webUser);
        }
    }
}
