//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFIS360WebApp.PersonPhysicalCharServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataObject", Namespace="http://localhost/AFIS360Webservice")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AFIS360WebApp.PersonPhysicalCharServiceRef.PersonPhysicalChar))]
    public partial class DataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        private System.Nullable<System.DateTime> CreationDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        private System.Nullable<System.DateTime> UpdateDateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> CreationDateTime {
            get {
                return this.CreationDateTimeField;
            }
            set {
                if ((this.CreationDateTimeField.Equals(value) != true)) {
                    this.CreationDateTimeField = value;
                    this.RaisePropertyChanged("CreationDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> UpdateDateTime {
            get {
                return this.UpdateDateTimeField;
            }
            set {
                if ((this.UpdateDateTimeField.Equals(value) != true)) {
                    this.UpdateDateTimeField = value;
                    this.RaisePropertyChanged("UpdateDateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonPhysicalChar", Namespace="http://localhost/AFIS360Webservice")]
    [System.SerializableAttribute()]
    public partial class PersonPhysicalChar : AFIS360WebApp.PersonPhysicalCharServiceRef.DataObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonIdField;
        
        private double HeightField;
        
        private double WeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EyeColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HairColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComplexionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthMarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdMarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        private System.DateTime DODField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonIdField, value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EyeColor {
            get {
                return this.EyeColorField;
            }
            set {
                if ((object.ReferenceEquals(this.EyeColorField, value) != true)) {
                    this.EyeColorField = value;
                    this.RaisePropertyChanged("EyeColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string HairColor {
            get {
                return this.HairColorField;
            }
            set {
                if ((object.ReferenceEquals(this.HairColorField, value) != true)) {
                    this.HairColorField = value;
                    this.RaisePropertyChanged("HairColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Complexion {
            get {
                return this.ComplexionField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplexionField, value) != true)) {
                    this.ComplexionField = value;
                    this.RaisePropertyChanged("Complexion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string BuildType {
            get {
                return this.BuildTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildTypeField, value) != true)) {
                    this.BuildTypeField = value;
                    this.RaisePropertyChanged("BuildType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string BirthMark {
            get {
                return this.BirthMarkField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthMarkField, value) != true)) {
                    this.BirthMarkField = value;
                    this.RaisePropertyChanged("BirthMark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string IdMark {
            get {
                return this.IdMarkField;
            }
            set {
                if ((object.ReferenceEquals(this.IdMarkField, value) != true)) {
                    this.IdMarkField = value;
                    this.RaisePropertyChanged("IdMark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime DOD {
            get {
                return this.DODField;
            }
            set {
                if ((this.DODField.Equals(value) != true)) {
                    this.DODField = value;
                    this.RaisePropertyChanged("DOD");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/AFIS360Webservice", ConfigurationName="PersonPhysicalCharServiceRef.PersonPhysicalCharServiceSoap")]
    public interface PersonPhysicalCharServiceSoap {
        
        // CODEGEN: Generating message contract since element name personId from namespace http://localhost/AFIS360Webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/AFIS360Webservice/GetPersonPhysicalChar", ReplyAction="*")]
        AFIS360WebApp.PersonPhysicalCharServiceRef.GetPersonPhysicalCharResponse GetPersonPhysicalChar(AFIS360WebApp.PersonPhysicalCharServiceRef.GetPersonPhysicalCharRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/AFIS360Webservice/GetPersonPhysicalChar", ReplyAction="*")]
        System.Threading.Tasks.Task<AFIS360WebApp.PersonPhysicalCharServiceRef.GetPersonPhysicalCharResponse> GetPersonPhysicalCharAsync(AFIS360WebApp.PersonPhysicalCharServiceRef.GetPersonPhysicalCharRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonPhysicalCharRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonPhysicalChar", Namespace="http://localhost/AFIS360Webservice", Order=0)]
        public AFIS360WebApp.PersonPhysicalCharServiceRef.GetPersonPhysicalCharRequestBody Body;
        
        public GetPersonPhysicalCharRequest() {
        }
        
        public GetPersonPhysicalCharRequest(AFIS360WebApp.PersonPhysicalCharServiceRef.GetPersonPhysicalCharRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/AFIS360Webservice")]
    public partial class GetPersonPhysicalCharRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string personId;
        
        public GetPersonPhysicalCharRequestBody() {
        }
        
        public GetPersonPhysicalCharRequestBody(string personId) {
            this.personId = personId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonPhysicalCharResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonPhysicalCharResponse", Namespace="http://localhost/AFIS360Webservice", Order=0)]
        public AFIS360WebApp.PersonPhysicalCharServiceRef.GetPersonPhysicalCharResponseBody Body;
        
        public GetPersonPhysicalCharResponse() {
        }
        
        public GetPersonPhysicalCharResponse(AFIS360WebApp.PersonPhysicalCharServiceRef.GetPersonPhysicalCharResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/AFIS360Webservice")]
    public partial class GetPersonPhysicalCharResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AFIS360WebApp.PersonPhysicalCharServiceRef.PersonPhysicalChar GetPersonPhysicalCharResult;
        
        public GetPersonPhysicalCharResponseBody() {
        }
        
        public GetPersonPhysicalCharResponseBody(AFIS360WebApp.PersonPhysicalCharServiceRef.PersonPhysicalChar GetPersonPhysicalCharResult) {
            this.GetPersonPhysicalCharResult = GetPersonPhysicalCharResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PersonPhysicalCharServiceSoapChannel : AFIS360WebApp.PersonPhysicalCharServiceRef.PersonPhysicalCharServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonPhysicalCharServiceSoapClient : System.ServiceModel.ClientBase<AFIS360WebApp.PersonPhysicalCharServiceRef.PersonPhysicalCharServiceSoap>, AFIS360WebApp.PersonPhysicalCharServiceRef.PersonPhysicalCharServiceSoap {
        
        public PersonPhysicalCharServiceSoapClient() {
        }
        
        public PersonPhysicalCharServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonPhysicalCharServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonPhysicalCharServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonPhysicalCharServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AFIS360WebApp.PersonPhysicalCharServiceRef.GetPersonPhysicalCharResponse AFIS360WebApp.PersonPhysicalCharServiceRef.PersonPhysicalCharServiceSoap.GetPersonPhysicalChar(AFIS360WebApp.PersonPhysicalCharServiceRef.GetPersonPhysicalCharRequest request) {
            return base.Channel.GetPersonPhysicalChar(request);
        }
        
        public AFIS360WebApp.PersonPhysicalCharServiceRef.PersonPhysicalChar GetPersonPhysicalChar(string personId) {
            AFIS360WebApp.PersonPhysicalCharServiceRef.GetPersonPhysicalCharRequest inValue = new AFIS360WebApp.PersonPhysicalCharServiceRef.GetPersonPhysicalCharRequest();
            inValue.Body = new AFIS360WebApp.PersonPhysicalCharServiceRef.GetPersonPhysicalCharRequestBody();
            inValue.Body.personId = personId;
            AFIS360WebApp.PersonPhysicalCharServiceRef.GetPersonPhysicalCharResponse retVal = ((AFIS360WebApp.PersonPhysicalCharServiceRef.PersonPhysicalCharServiceSoap)(this)).GetPersonPhysicalChar(inValue);
            return retVal.Body.GetPersonPhysicalCharResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AFIS360WebApp.PersonPhysicalCharServiceRef.GetPersonPhysicalCharResponse> AFIS360WebApp.PersonPhysicalCharServiceRef.PersonPhysicalCharServiceSoap.GetPersonPhysicalCharAsync(AFIS360WebApp.PersonPhysicalCharServiceRef.GetPersonPhysicalCharRequest request) {
            return base.Channel.GetPersonPhysicalCharAsync(request);
        }
        
        public System.Threading.Tasks.Task<AFIS360WebApp.PersonPhysicalCharServiceRef.GetPersonPhysicalCharResponse> GetPersonPhysicalCharAsync(string personId) {
            AFIS360WebApp.PersonPhysicalCharServiceRef.GetPersonPhysicalCharRequest inValue = new AFIS360WebApp.PersonPhysicalCharServiceRef.GetPersonPhysicalCharRequest();
            inValue.Body = new AFIS360WebApp.PersonPhysicalCharServiceRef.GetPersonPhysicalCharRequestBody();
            inValue.Body.personId = personId;
            return ((AFIS360WebApp.PersonPhysicalCharServiceRef.PersonPhysicalCharServiceSoap)(this)).GetPersonPhysicalCharAsync(inValue);
        }
    }
}
